// Code generated by 'cfn generate', changes will be undone by the next invocation. DO NOT EDIT.
// Updates to this type are made my editing the schema file and executing the 'generate' command.
package resource

// Model is autogenerated from the json schema
type Model struct {
	Url            *string  `json:",omitempty"`
	ClientIDList   []string `json:",omitempty"`
	ThumbprintList []string `json:",omitempty"`
	Arn            *string  `json:",omitempty"`
	Name           *string  `json:",omitempty"`
}
