package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	Url            *string  `json:",omitempty"`
	ClientIDList   []string `json:",omitempty"`
	ThumbprintList []string `json:",omitempty"`
	Arn            *string  `json:",omitempty"`
	Name           *string  `json:",omitempty"`
}
