package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	Url            *encoding.String   `json:"Url,omitempty"`
	ClientIDList   []*encoding.String `json:"ClientIDList,omitempty"`
	ThumbprintList []*encoding.String `json:"ThumbprintList,omitempty"`
	Arn            *encoding.String   `json:"Arn,omitempty"`
	Name           *encoding.String   `json:"Name,omitempty"`
}
